packages:
  - apps/*
  - packages/*
  - infra/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram
  - unrs-resolver
