name: 'Build Project'
description: 'Setup Node.js environment, install dependencies, and run build pipeline with optional checks'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10'

  check-dependencies:
    description: 'Run dependency check (pnpm depchk)'
    required: false
    default: 'true'

  check-format:
    description: 'Run format check (pnpm check:format)'
    required: false
    default: 'true'

  run-lint:
    description: 'Run linting (pnpm lint)'
    required: false
    default: 'true'

  run-tests:
    description: 'Run tests (pnpm test)'
    required: false
    default: 'true'

  build-filter:
    description: 'Build filter for specific packages/apps (e.g., app-vite)'
    required: true

  build-environment:
    description: 'Build environment (development, staging, production)'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Validate input
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Validate input"
        echo "──────────────────────────────────────"
        echo " "
        if ! [ -n "${{ inputs.build-filter }}" ]; then
          echo "No build filter provided."
          exit 1
        fi

        echo "Input is valid:"
        echo " "
        echo "Node.js version: ${{ inputs.node-version }}"
        echo "pnpm version: ${{ inputs.pnpm-version }}"
        echo "Check dependencies: ${{ inputs.check-dependencies }}"
        echo "Check format: ${{ inputs.check-format }}"
        echo "Run lint: ${{ inputs.run-lint }}"
        echo "Run tests: ${{ inputs.run-tests }}"
        echo "Build filter: ${{ inputs.build-filter }}"
        echo "Build environment: ${{ inputs.build-environment }}"
        echo " "

    - shell: bash
      run: |
        echo " "
        echo " "
        echo "Setup pnpm"
        echo "──────────────────────────────────────"
        echo " "
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - shell: bash
      run: |
        echo " "
        echo " "
        echo "Setup Node.js"
        echo "──────────────────────────────────────"
        echo " "
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Install dependencies"
        echo "──────────────────────────────────────"
        echo " "
        pnpm install

    - name: Check dependencies
      if: inputs.check-dependencies == 'true'
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Check dependencies"
        echo "──────────────────────────────────────"
        echo " "
        BUILD_ENVIRONMENT=${{ inputs.build-environment }} dotenv -- pnpm depchk

    - name: Check format
      if: inputs.check-format == 'true'
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Check format"
        echo "──────────────────────────────────────"
        echo " "
        BUILD_ENVIRONMENT=${{ inputs.build-environment }} dotenv -- pnpm check:format

    - name: Build
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Build (${{ inputs.build-filter }})"
        echo "──────────────────────────────────────"
        echo " "
        if [ -n "${{ inputs.build-filter }}" ]; then
          BUILD_ENVIRONMENT=${{ inputs.build-environment }} BUNDLER=${{ inputs.build-filter }} dotenv -- sh -c 'turbo run build --filter "${{ inputs.build-filter }}"'
        else
          BUILD_ENVIRONMENT=${{ inputs.build-environment }} dotenv -- pnpm build
        fi

    - name: Lint
      if: inputs.run-lint == 'true'
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Lint"
        echo "──────────────────────────────────────"
        echo " "
        BUILD_ENVIRONMENT=${{ inputs.build-environment }} dotenv -- pnpm lint

    - name: Test
      if: inputs.run-tests == 'true'
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Test"
        echo "──────────────────────────────────────"
        echo " "
        BUILD_ENVIRONMENT=${{ inputs.build-environment }} dotenv -- pnpm test
