name: 'Build Project'
description: 'Setup Node.js environment, install dependencies, and run build pipeline with optional checks using Turborepo parallel execution'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10'

  check-dependencies:
    description: 'Run dependency check (pnpm depchk)'
    required: false
    default: 'true'

  check-format:
    description: 'Run format check (pnpm check:format)'
    required: false
    default: 'true'

  run-lint:
    description: 'Run linting (pnpm lint)'
    required: false
    default: 'true'

  run-tests:
    description: 'Run tests (pnpm test)'
    required: false
    default: 'true'

  # TODO: not needed because of build?
  # run-type-check:
  #   description: 'Run TypeScript type checking (pnpm test:type)'
  #   required: false
  #   default: 'true'

  build-filter:
    description: 'Build filter for specific packages/apps (e.g., app-vite)'
    required: true

  build-environment:
    description: 'Build environment (development, staging, production)'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Validate input
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Validate input"
        echo "──────────────────────────────────────"
        echo " "
        if ! [ -n "${{ inputs.build-filter }}" ]; then
          echo "No build filter provided."
          exit 1
        fi

        echo "Input is valid:"
        echo " "
        echo "Node.js version: ${{ inputs.node-version }}"
        echo "pnpm version: ${{ inputs.pnpm-version }}"
        echo "Check dependencies: ${{ inputs.check-dependencies }}"
        echo "Check format: ${{ inputs.check-format }}"
        echo "Run lint: ${{ inputs.run-lint }}"
        echo "Run tests: ${{ inputs.run-tests }}"
        echo "Run type check: ${{ inputs.run-type-check }}"
        echo "Build filter: ${{ inputs.build-filter }}"
        echo "Build environment: ${{ inputs.build-environment }}"
        echo " "

    - shell: bash
      run: |
        echo " "
        echo " "
        echo "Setup pnpm"
        echo "──────────────────────────────────────"
        echo " "
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - shell: bash
      run: |
        echo " "
        echo " "
        echo "Setup Node.js"
        echo "──────────────────────────────────────"
        echo " "
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Install dependencies"
        echo "──────────────────────────────────────"
        echo " "
        pnpm install

    - name: Check dependencies
      if: inputs.check-dependencies == 'true'
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Check dependencies"
        echo "──────────────────────────────────────"
        echo " "
        BUILD_ENVIRONMENT=${{ inputs.build-environment }} pnpm depchk

    - name: Build and run quality checks in parallel
      shell: bash
      run: |
        echo " "
        echo " "
        echo "Build and run quality checks in parallel"
        echo "──────────────────────────────────────"
        echo " "

        # Build tasks list based on inputs
        TASKS=""

        # Always include build for the specific filter
        TASKS="build"

        # Add conditional tasks
        if [ "${{ inputs.check-format }}" = "true" ]; then
          TASKS="$TASKS check:format"
        fi

        if [ "${{ inputs.run-lint }}" = "true" ]; then
          TASKS="$TASKS lint"
        fi

        if [ "${{ inputs.run-tests }}" = "true" ]; then
          TASKS="$TASKS test"
        fi

        # if [ "${{ inputs.run-type-check }}" = "true" ]; then
        #   TASKS="$TASKS test:type"
        # fi

        echo "Running tasks in parallel: $TASKS"
        echo " "

        # Run turbo with all tasks, filtered to the specific build target
        BUILD_ENVIRONMENT=${{ inputs.build-environment }} BUNDLER=${{ inputs.build-filter }} pnpm turbo $TASKS --filter "${{ inputs.build-filter }}"

# # Run checks across entire monorepo, but build only the filtered app
# if [ -n "$TASKS" ]; then
#   echo "Running global checks and filtered build..."
#   BUILD_ENVIRONMENT=${{ inputs.build-environment }} BUNDLER=${{ inputs.build-filter }} pnpm turbo check:format lint test test:type
#   BUILD_ENVIRONMENT=${{ inputs.build-environment }} BUNDLER=${{ inputs.build-filter }} pnpm turbo build --filter "${{ inputs.build-filter }}"
# else
#   BUILD_ENVIRONMENT=${{ inputs.build-environment }} BUNDLER=${{ inputs.build-filter }} pnpm turbo build --filter "${{ inputs.build-filter }}"
# fi
