---
name: CloudFormation unit tests
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
      - run: gem install cfn-nag
      - uses: actions/checkout@v2
      # Run Tests
      - name: CloudFormation unit tests
        run: make test-cfn
