on:
    workflow_dispatch:
    # push

name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --filter app-vite

      - name: Publish
        uses: netlify/actions/cli@master
        with:
            args: deploy --dir=apps/app-vite/dist --functions=functions
        env:
            # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: DEBUG=WILL BE REMOVED
        run: echo ${{ steps.publish.NETLIFY_PREVIEW_URL }}

