name: Publish on Netlify (Custom)

on:
  workflow_dispatch:
    inputs:
      bundler:
        type: choice
        description: "Bundler"
        required: true
        options:
          - app-vite
          - app-webpack
          - app-esbuild

      environment:
        type: choice
        description: "Environment"
        required: true
        options:
          - production
          - staging

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment
        run: echo "Environment=${{ github.event.inputs.environment }} - Bundler=${{github.event.inputs.bundler}}, BRANCH_NAME=$BRANCH_NAME"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Netlify
        run: npm install netlify-cli@17.36.4 -g

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: BUILD_ENVIRONMENT=${{ github.event.inputs.environment }} pnpm build --filter ${{ github.event.inputs.bundler }}

      - name: Log Build output
        run: ls apps/${{ github.event.inputs.bundler }}/dist

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          prod_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --dir apps/${{ github.event.inputs.bundler }}/dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --filter ${{ github.event.inputs.bundler }} \
            $prod_flag

      - name: DEBUG=WILL BE REMOVED
        run: echo ${{ steps.netlify_deploy.outputs.NETLIFY_PREVIEW_URL }}
